name: g_customer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  http: ^0.13.5
  intl: ^0.17.0
  image: ^3.2.0
  lottie: ^1.4.1
  get_it: ^7.2.0
  flash: ^2.0.3+3
  shimmer: ^2.0.0
  location: ^4.4.0
  geocoding: ^2.0.4
  auto_route: ^4.2.1
  google_place: ^0.4.7
  sms_autofill: ^2.2.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5
  flutter_svg: ^1.1.1+1
  flutter_remix: ^0.0.3
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  flutter_stripe: ^5.0.0
  google_sign_in: ^5.4.1
  cloud_firestore: ^3.4.6
  carousel_slider: ^4.1.1
  flutter_riverpod: ^1.0.4
  razorpay_flutter: ^1.3.2
  flutter_braintree: ^2.3.1
  connectivity_plus: ^2.3.6
#  flutter_paystack: ^1.0.5+1
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  sliding_up_panel: ^2.0.0+1
  freezed_annotation: ^2.1.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.0.15
  firebase_messaging: ^13.0.0
  google_maps_flutter: ^2.2.0
  flutter_html: ^3.0.0-alpha.6
  flutter_screenutil: ^5.5.3+2
  cached_network_image: ^3.2.1
  flutter_facebook_auth: ^4.4.1+1
  flutter_local_notifications: ^9.9.1
  expansion_tile_card: ^2.0.0

  video_player: ^2.5.1
  video_compress: ^3.1.2
  camera: ^0.10.2+1
  image_picker: ^0.8.6+1
  fluttertoast: ^8.1.2
  path_provider: ^2.0.12
  chewie: ^1.4.0
  file_selector: ^0.9.2+2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/png/app_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/lottie/
